---
azs:
- name: z1
  cloud_properties: { zone: europe-west1-b }
- name: z2
  cloud_properties: { zone: europe-west1-c }
- name: z3
  cloud_properties: { zone: europe-west1-d }

vm_types:
- name: server
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_type: pd-standard
- name: node
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_type: pd-standard
    target_pool: nodes
- name: compilation
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_type: pd-standard

disk_types:
- name: server
  disk_size: 5000
- name: node
  disk_size: 10000

networks:
- name: servers
  type: manual
  subnets:
  - range: 10.0.2.0/24
    gateway: 10.0.2.1
    azs: [z1, z2, z3]
    cloud_properties:
      network_name: hashistack
      subnetwork_name: hashistack-servers
      tags: [bosh-agent, consul, vault, nomad]
- name: nodes
  type: manual
  subnets:
  - range: 10.0.3.0/24
    gateway: 10.0.3.1
    azs: [z1, z2, z3]
    cloud_properties:
      network_name: hashistack
      subnetwork_name: hashistack-nodes
      tags: [bosh-agent, consul-agent, nomad-node]

compilation:
  workers: 4
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: servers
