---
params:
  region: (( param "Please specify the region of this deployment" ))

  nomad_vault_role: nomad-cluster

  node_network:   default
  node_disk_type: default
  node_vm_type:   default
  node_vm_extensions: []
  node_instances: 3
