---
params:
  region: (( param "Please specify the region of this deployment" ))

  nomad_vault_role: nomad-cluster

  node_network: nodes
  node_disk_pool: node
  node_vm_type: node
  node_instances: 3
