---
params:
  datacenter: (( param "Please specify the datacenter for this deployment" ))
  verify_ssl: true
  server_instances: 5

  consul_network:   consul_network
  consul_disk_pool: server
  consul_vm_type:   small

  availability_zones: [z1, z2, z3]

  stemcell_os: ubuntu-trusty
  stemcell_version: latest
