---
params:
  datacenter: (( param "Please specify the datacenter for this deployment" ))
  verify_ssl: true
  server_instances: 3

  server_network:   servers
  server_disk_type: server
  server_vm_type:   server

  availability_zones: [z1, z2, z3]

  stemcell_os: ubuntu-trusty
  stemcell_version: latest
