---
params:
  datacenter: (( param "Please specify the datacenter for this deployment" ))

  hashistack_network:   hashistack-network
  consul_disk_pool: server
  consul_vm_type:   small

  consul_verify_incoming: true

  availability_zones: [z1, z2, z3]

  stemcell_os: ubuntu-trusty
  stemcell_version: latest
