---
params:
  datacenter: (( param "Please specify the datacenter for this deployment" ))
  verify_ssl: true
  server_instances: 3
  resolvconf_override: true

  server_network:   default
  server_disk_type: default
  server_vm_type:   default

  availability_zones: [z1, z2, z3]

  stemcell_os: ubuntu-trusty
  stemcell_version: latest
